---
# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: Install opensafely cli tool
    # runs when workspace initially created, and as pre-build
    init: |
        pip install opensafely
        opensafely pull --project project.yaml
  - name: Update opensafely
    # run every time you open a workspace
    command:
        command -v opensafely && opensafely upgrade
  - name: setup environment
    command: test -f .gitpod.env && { set -a; . .gitpod.env; set +a; }


github:
  prebuilds:
    # enable for the default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: true
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
    # add a check to pull requests (defaults to true)
    addCheck: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: true
    # add a "Review in Gitpod" button to the pull request's description (defaults to false)
    addBadge: false

vscode:
  extensions:
    - ms-python.python
    - vscode.html-language-features
    - redhat.vscode-yaml
    - ikuyadeu.r
    - randomfractalsinc.vscode-data-preview
