version: '3.0'

expectations:
  population_size: 1000

actions:

# Extract data
# When argument --index-date-range is changed, change has to be made in ./analysis/config.R and ./analysis/config.py too
  generate_study_population:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --skip-existing --output-format=csv.gz --index-date-range "2020-02-01 to 2020-08-01 by month"
    outputs:
      highly_sensitive:
        cohort: output/input_*.csv.gz

# Extract ethnicity
  generate_study_population_ethnicity:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_ethnicity --output-format=csv.gz
    outputs:
      highly_sensitive:
        cohort: output/input_ethnicity.csv.gz

# Join data
  join_data:
    run: python:latest analysis/join_ethnicity.py
    needs: [generate_study_population, generate_study_population_ethnicity]
    outputs:
      highly_sensitive:
        cohort: output/input*.csv.gz

# Calculate mortality rates (crude + subgroup specific)
  calculate_measures:
    run: cohortextractor:latest generate_measures --study-definition study_definition
    needs: [join_data]
    outputs:
      moderately_sensitive:
        measure: output/measure_*_mortality_rate.csv

# Standardise crude mortality rate
  standardise_crude_rates:
    run: r:latest analysis/crude_rates_standardise.R
    needs: [calculate_measures]
    outputs:
      moderately_sensitive:
        rds: output/rates/crude_*monthly_std.rds 

# Standardise subgroup specific mortality rates
  standardise_subgroup_rates:
    run: r:latest analysis/subgroups_rates_standardise.R
    needs: [calculate_measures]
    outputs:
      moderately_sensitive:
        rds: output/rates/*_monthly_std.rds 