version: '3.0'

expectations:
  population_size: 1000

actions:

# Extract data
  generate_study_population:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --output-dir=output/data
    outputs:
      highly_sensitive:
        cohort: output/data/input.csv

# Extract ethnicity
  generate_study_population_ethnicity:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_ethnicity --output-dir=output/data
    outputs:
      highly_sensitive:
        cohort: output/data/input_ethnicity.csv

# Join data
  join_data:
    run: r:latest analysis/data_join.R
    needs: [generate_study_population, generate_study_population_ethnicity]
    outputs:
      highly_sensitive:
        data: output/data/data_joined.rds