version: '3.0'

expectations:
  population_size: 1000

actions:

# Extract data
  generate_study_population:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --skip-existing --output-format=csv.gz --index-date-range "2020-02-01 to 2021-12-01 by month"
    outputs:
      highly_sensitive:
        cohort: output/input_*.csv.gz

# Extract ethnicity
  generate_study_population_ethnicity:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_ethnicity --output-format=csv.gz
    outputs:
      highly_sensitive:
        cohort: output/input_ethnicity.csv.gz

# Join data
  join_data:
    run: r:latest analysis/data_join.R
    needs: [generate_study_population, generate_study_population_ethnicity]
    outputs:
      highly_sensitive:
        data: output/input*.csv.gz

# Calculate mortality rates
  calculate_measures:
    run: cohortextractor:latest generate_measures --study-definition study_definition
    needs: [join_data]
    outputs:
      moderately_sensitive:
        measure: output/measure_*_rate.csv

# Standardise mortality rates
  standardise_crude_rates:
    run: r:latest analysis/standardise_crude_mortality_rates.R
    needs: [calculate_measures]
    outputs:
      moderately_sensitive:
        measure: output/rates/crude_monthly_std.csv 