version: '3.0'

expectations:
  population_size: 1000

actions:

# Extract data
  generate_study_population:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --skip-existing --index-date-range "2020-02-01 to 2021-12-01 by month"
    outputs:
      highly_sensitive:
        cohort: output/input_*.csv

# Extract ethnicity
  generate_study_population_ethnicity:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_ethnicity
    outputs:
      highly_sensitive:
        cohort: output/input_ethnicity.csv

# Join data
  join_data:
    run: r:latest analysis/data_join.R
    needs: [generate_study_population, generate_study_population_ethnicity]
    outputs:
      highly_sensitive:
        data: output/input*.csv

# Calculate mortality rates
  calculate_measures:
    run: cohortextractor:latest generate_measures --study-definition study_definition
    needs: [join_data]
    outputs:
      moderately_sensitive:
        measure: output/measure_*_rate.csv